version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      MONGO_INITDB_ROOT_USERNAME: postgres
      MONGO_INITDB_ROOT_PASSWORD: postgres
    networks:
      default:
        aliases:
          - postgres

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      default:
        aliases:
          - redis